version: "3.7"

#service template
x-discord-bot:
  &discord-bot
  image: discord-statupdater:prod
  restart: unless-stopped
  env_file:
    - .env

#This is the base service for production and development
#list of services
services:
  discord-stats-0:
    <<: *discord-bot
    container_name: shard-0
    environment:
      SHARD_ID: 0
#  discord-stats-1:
#    <<: *discord-bot
#    container_name: shard-1
#    environment:
#      SHARD_ID: 1
#  discord-stats-2:
#    <<: *discord-bot
#    container_name: shard-2
#    environment:
#      SHARD_ID: 2
#  discord-stats-3:
#    <<: *discord-bot
#    container_name: shard-3
#    environment:
#      SHARD_ID: 3